export const CHECKLIST_TASKS = [
  { section: 'PLANNING FOUNDATIONS', task: 'Set wedding date', assignedTo: 'Both' },
  { section: 'PLANNING FOUNDATIONS', task: 'Set overall budget', assignedTo: 'Both' },
  { section: 'PLANNING FOUNDATIONS', task: 'Write guest list draft', assignedTo: 'Both' },
  { section: 'PLANNING FOUNDATIONS', task: 'Choose and book ceremony venue', assignedTo: 'Both' },
  { section: 'PLANNING FOUNDATIONS', task: 'Choose and book reception venue', assignedTo: 'Both' },

  { section: 'LEGAL', task: 'Lodge Notice of Intended Marriage (NOIM) with celebrant', assignedTo: 'Both', notes: 'Must be done at least 1 month before ceremony — do ASAP' },
  { section: 'LEGAL', task: 'Choose and book celebrant', assignedTo: 'Both' },
  { section: 'LEGAL', task: 'Confirm legal name change process post-wedding (if applicable)', assignedTo: 'Cyn' },
  { section: 'LEGAL', task: 'Submit marriage certificate after ceremony', assignedTo: 'Both' },
  { section: 'LEGAL', task: 'Update legal documents after name change — passport, licence, bank', assignedTo: 'Cyn' },

  { section: 'VENDORS', task: 'Research and shortlist photographers', assignedTo: 'Cyn' },
  { section: 'VENDORS', task: 'Book wedding photographer', assignedTo: 'Both' },
  { section: 'VENDORS', task: 'Research and shortlist videographers', assignedTo: 'Cyn' },
  { section: 'VENDORS', task: 'Book wedding videographer', assignedTo: 'Both' },
  { section: 'VENDORS', task: 'Book florist and confirm arrangements', assignedTo: 'Cyn' },
  { section: 'VENDORS', task: 'Confirm final florals brief and delivery time', assignedTo: 'Cyn' },
  { section: 'VENDORS', task: 'Book DJ or band', assignedTo: 'Tim' },
  { section: 'VENDORS', task: 'Send song requests and do-not-play list to NOBU', assignedTo: 'Tim' },
  { section: 'VENDORS', task: 'Book photobooth', assignedTo: 'Cyn' },
  { section: 'VENDORS', task: 'Confirm photobooth delivery and setup details', assignedTo: 'Cyn' },
  { section: 'VENDORS', task: 'Chase reception venue — menu sign-off, floor plan, AV setup', assignedTo: 'Both' },
  { section: 'VENDORS', task: 'Confirm videographer shot list and schedule', assignedTo: 'Both' },
  { section: 'VENDORS', task: 'Confirm all vendor final payments', assignedTo: 'Both' },
  { section: 'VENDORS', task: 'Build a vendor contact sheet for the day', assignedTo: 'Both' },

  { section: 'WEDDING PARTY & FASHION', task: 'Choose wedding party (bridesmaids & groomsmen)', assignedTo: 'Both' },
  { section: 'WEDDING PARTY & FASHION', task: 'Shop for wedding dress', assignedTo: 'Cyn' },
  { section: 'WEDDING PARTY & FASHION', task: 'Order wedding dress', assignedTo: 'Cyn' },
  { section: 'WEDDING PARTY & FASHION', task: 'Book dress alterations', assignedTo: 'Cyn' },
  { section: 'WEDDING PARTY & FASHION', task: 'Shop for wedding shoes & accessories', assignedTo: 'Cyn' },
  { section: 'WEDDING PARTY & FASHION', task: 'Break in wedding shoes before the day', assignedTo: 'Cyn' },
  { section: 'WEDDING PARTY & FASHION', task: "Choose and order groom's attire", assignedTo: 'Tim' },
  { section: 'WEDDING PARTY & FASHION', task: "Book groom's alterations", assignedTo: 'Tim' },
  { section: 'WEDDING PARTY & FASHION', task: 'Choose bridesmaid outfits', assignedTo: 'Cyn' },
  { section: 'WEDDING PARTY & FASHION', task: 'Choose groomsmen attire', assignedTo: 'Tim' },
  { section: 'WEDDING PARTY & FASHION', task: 'Buy gifts for bridesmaids', assignedTo: 'Cyn' },
  { section: 'WEDDING PARTY & FASHION', task: 'Buy gifts for groomsmen', assignedTo: 'Tim' },

  { section: 'BEAUTY & WELLNESS', task: 'Book hair & makeup artist', assignedTo: 'Cyn' },
  { section: 'BEAUTY & WELLNESS', task: 'Schedule hair & makeup trial', assignedTo: 'Cyn' },
  { section: 'BEAUTY & WELLNESS', task: 'Attend first hair & makeup trial', assignedTo: 'Cyn' },
  { section: 'BEAUTY & WELLNESS', task: 'Attend second hair & makeup trial (if needed)', assignedTo: 'Cyn' },
  { section: 'BEAUTY & WELLNESS', task: 'Book pre-wedding spa treatments', assignedTo: 'Cyn' },
  { section: 'BEAUTY & WELLNESS', task: 'Book pre-wedding haircuts & treatments', assignedTo: 'Both' },

  { section: 'STATIONERY & COMMUNICATIONS', task: 'Send save-the-dates', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Design and print invitations', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Send invitations', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Finalise guest RSVPs and dietary requirements', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Order ceremony programs', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Order menus and place cards', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Order signage — welcome sign, seating chart', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Order bonbonniere', assignedTo: 'Cyn' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Order wedding rings', assignedTo: 'Both' },
  { section: 'STATIONERY & COMMUNICATIONS', task: 'Order vow books', assignedTo: 'Both' },

  { section: 'CEREMONY PLANNING', task: 'Write personal vows', assignedTo: 'Both' },
  { section: 'CEREMONY PLANNING', task: 'Plan ceremony structure and order of events with celebrant', assignedTo: 'Both' },
  { section: 'CEREMONY PLANNING', task: 'Choose ceremony music — processional, signing, recessional', assignedTo: 'Both' },
  { section: 'CEREMONY PLANNING', task: 'Confirm readings or any special elements in ceremony', assignedTo: 'Both' },
  { section: 'CEREMONY PLANNING', task: 'Plan ring bearer / flower girl roles (if applicable)', assignedTo: 'Both' },
  { section: 'CEREMONY PLANNING', task: 'Arrange rehearsal and rehearsal dinner', assignedTo: 'Both' },

  { section: 'RECEPTION — SPEECHES', task: 'Confirm who is giving speeches', assignedTo: 'Both' },
  { section: 'RECEPTION — SPEECHES', task: 'Brief all speakers — order, time limit, tone', assignedTo: 'Both' },
  { section: 'RECEPTION — SPEECHES', task: 'Confirm MC and provide full run sheet', assignedTo: 'Both' },
  { section: 'RECEPTION — SPEECHES', task: "Write Tim's speech", assignedTo: 'Tim' },
  { section: 'RECEPTION — SPEECHES', task: "Write Cyn's speech (if doing one)", assignedTo: 'Cyn' },
  { section: 'RECEPTION — SPEECHES', task: 'Collect and organise any video tributes or slideshows', assignedTo: 'Both' },

  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Choose first dance song', assignedTo: 'Both' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Decide on first dance style — freestyle or choreographed', assignedTo: 'Both' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Book and attend first dance lessons (if choreographed)', assignedTo: 'Both' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Plan bridal party entrance — order, song, walk style', assignedTo: 'Both' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Choose bridal party entrance song', assignedTo: 'Both' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Plan parent dances (father-daughter, mother-son) and songs', assignedTo: 'Both' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Plan any group dances or special performances', assignedTo: 'Both' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Brief NOBU on full music timeline — entrance, first dance, parent dances, party', assignedTo: 'Tim' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Plan bouquet toss — timing and song', assignedTo: 'Cyn' },
  { section: 'RECEPTION — DANCES & ENTERTAINMENT', task: 'Plan cake cutting — timing and song', assignedTo: 'Both' },

  { section: 'RECEPTION — LOGISTICS', task: 'Create seating plan', assignedTo: 'Both' },
  { section: 'RECEPTION — LOGISTICS', task: 'Create full wedding day run sheet', assignedTo: 'Both' },
  { section: 'RECEPTION — LOGISTICS', task: 'Share run sheet with MC, celebrant, and key vendors', assignedTo: 'Both' },
  { section: 'RECEPTION — LOGISTICS', task: 'Assign someone to manage tips and cash payments on the day', assignedTo: 'Both' },
  { section: 'RECEPTION — LOGISTICS', task: 'Assign someone to collect gifts and cards at reception', assignedTo: 'Both' },
  { section: 'RECEPTION — LOGISTICS', task: 'Build wedding day emergency kit — safety pins, stain remover, painkillers', assignedTo: 'Cyn' },

  { section: 'ACCOMMODATION & TRAVEL', task: 'Arrange accommodation — night before and night of wedding', assignedTo: 'Both' },
  { section: 'ACCOMMODATION & TRAVEL', task: 'Arrange transport for bridal party on the day', assignedTo: 'Both' },
  { section: 'ACCOMMODATION & TRAVEL', task: 'Plan honeymoon destination', assignedTo: 'Both' },
  { section: 'ACCOMMODATION & TRAVEL', task: 'Book honeymoon flights', assignedTo: 'Both' },
  { section: 'ACCOMMODATION & TRAVEL', task: 'Book honeymoon accommodation', assignedTo: 'Both' },
  { section: 'ACCOMMODATION & TRAVEL', task: 'Pack for honeymoon', assignedTo: 'Both' },

  { section: 'PRE-WEDDING EVENTS', task: "Plan hen's night", assignedTo: 'Cyn' },
  { section: 'PRE-WEDDING EVENTS', task: "Plan bucks night", assignedTo: 'Tim' },

  { section: 'POST-WEDDING', task: 'Return any hired items — suits, equipment', assignedTo: 'Both' },
  { section: 'POST-WEDDING', task: 'Write and send thank-you cards', assignedTo: 'Both' },
  { section: 'POST-WEDDING', task: 'Back up all wedding photos and videos', assignedTo: 'Both' },
];
